### ISSUE TITLE
Initialise this repo with Playwright

### ISSUE THREAD

**Issue by nabarunchakma** [liyachakma/DHL-Playwright#1]
Either choose `npm` or `yarn`.  Though `yarn` is preferable.

Reference for initialisation: https://playwright.dev/docs/intro

Once installed, complete the following activities.

- Run the example test - https://playwright.dev/docs/intro#running-the-example-test
- View the HTML reports - https://playwright.dev/docs/intro#html-test-reports
- Run the test in UI mode - https://playwright.dev/docs/intro#running-the-example-test-in-ui-mode
- Update playwright - https://playwright.dev/docs/intro#updating-playwright

**Comment by liyachakma** [comment]
This is complete.

**Comment by nabarunchakma** [comment]
You should use the close button to close the issue.
